package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// =================================================================
// Minimalist Monochrome / Noir High-Contrast Black and White Theme
// =================================================================

// Material 3 Light Scheme Colors (Pure Crisp White Canvas with Deep Pitch Black Contrast)
val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF18181B)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFF27272A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4E4E7)
val md_theme_light_onSecondaryContainer = Color(0xFF09090B)
val md_theme_light_tertiary = Color(0xFF3F3F46)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF4F4F5)
val md_theme_light_onTertiaryContainer = Color(0xFF18181B)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_outline = Color(0xFF71717A)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFF4F4F5)
val md_theme_light_onSurfaceVariant = Color(0xFF52525B)
val md_theme_light_inverseSurface = Color(0xFF18181B)
val md_theme_light_inverseOnSurface = Color(0xFFF4F4F5)
val md_theme_light_inversePrimary = Color(0xFFFFFFFF)
val md_theme_light_surfaceTint = Color(0xFF000000)
val md_theme_light_outlineVariant = Color(0xFFE4E4E7)
val md_theme_light_scrim = Color(0xFF000000)

// Material 3 Dark Scheme Colors (Pure OLED Pitch Black Canvas with Stark Pure White Contrast)
val md_theme_dark_primary = Color(0xFFFFFFFF)
val md_theme_dark_onPrimary = Color(0xFF000000)
val md_theme_dark_primaryContainer = Color(0xFF27272A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFFE4E4E7)
val md_theme_dark_onSecondary = Color(0xFF000000)
val md_theme_dark_secondaryContainer = Color(0xFF18181B)
val md_theme_dark_onSecondaryContainer = Color(0xFFF4F4F5)
val md_theme_dark_tertiary = Color(0xFFD4D4D8)
val md_theme_dark_onTertiary = Color(0xFF000000)
val md_theme_dark_tertiaryContainer = Color(0xFF27272A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_error = Color(0xFFEF4444)
val md_theme_dark_onError = Color(0xFF000000)
val md_theme_dark_errorContainer = Color(0xFF450A0A)
val md_theme_dark_onErrorContainer = Color(0xFFFEE2E2)
val md_theme_dark_outline = Color(0xFF71717A)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF000000)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF121214)
val md_theme_dark_onSurfaceVariant = Color(0xFFA1A1AA)
val md_theme_dark_inverseSurface = Color(0xFFF4F4F5)
val md_theme_dark_inverseOnSurface = Color(0xFF18181B)
val md_theme_dark_inversePrimary = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFFFFF)
val md_theme_dark_outlineVariant = Color(0xFF27272A)
val md_theme_dark_scrim = Color(0xFF000000)

// Helper aliases for seamless compatibility across existing screens
val CinemaBlack = Color(0xFF000000)
val CinemaSurface = Color(0xFF09090B)
val CinemaSurfaceVariant = Color(0xFF18181B)
val CinemaSurfaceElevated = Color(0xFF27272A)
val CinemaCardBorder = Color(0x33FFFFFF)
val CinemaCardBorderHover = Color(0x66FFFFFF)

val CinemaAccent = Color(0xFFFFFFFF)
val CinemaAccentHover = Color(0xFFE4E4E7)
val CinemaAccentContainer = Color(0xFF27272A)
val CinemaAccentGlow = Color(0x40FFFFFF)

val CinemaRed = Color(0xFFFFFFFF)
val CinemaRedHover = Color(0xFFE4E4E7)
val CinemaRedContainer = Color(0xFF27272A)
val CinemaRedGlow = Color(0x40FFFFFF)

val CinemaViolet = Color(0xFFFFFFFF)
val CinemaVioletHover = Color(0xFFE4E4E7)
val CinemaVioletContainer = Color(0xFF27272A)
val CinemaVioletGlow = Color(0x40FFFFFF)

val CinemaCyan = Color(0xFFFFFFFF)
val CinemaAmber = Color(0xFFFFFFFF)
val CinemaGreen = Color(0xFFE4E4E7)
val CinemaDataSaverGreen = Color(0xFFE4E4E7)

val TextPrimary = Color(0xFFFFFFFF)
val TextSecondary = Color(0xFFA1A1AA)
val TextMuted = Color(0xFF71717A)

val GlassBackground = Color(0xEE09090B)
val GlassHighlight = Color(0x26FFFFFF)
val GlassBorder = Color(0x33FFFFFF)
